/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicResultsRouteImport } from './routes/api/public/results'
import { Route as ApiPublicSignalsRouteImport } from './routes/api/public/signals'
import { Route as ApiPublicVipRouteImport } from './routes/api/public/vip'
import { Route as ApiPublicVipSetVipRouteImport } from './routes/api/public/vip/set-vip'
import { Route as ApiPublicVipSyncRouteImport } from './routes/api/public/vip/sync'
import { Route as ApiPublicVipUsersRouteImport } from './routes/api/public/vip/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResultsRoute = ApiPublicResultsRouteImport.update({
  id: '/api/public/results',
  path: '/api/public/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSignalsRoute = ApiPublicSignalsRouteImport.update({
  id: '/api/public/signals',
  path: '/api/public/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVipRoute = ApiPublicVipRouteImport.update({
  id: '/api/public/vip',
  path: '/api/public/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVipSetVipRoute = ApiPublicVipSetVipRouteImport.update({
  id: '/set-vip',
  path: '/set-vip',
  getParentRoute: () => ApiPublicVipRoute,
} as any)
const ApiPublicVipSyncRoute = ApiPublicVipSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => ApiPublicVipRoute,
} as any)
const ApiPublicVipUsersRoute = ApiPublicVipUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ApiPublicVipRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/results': typeof ApiPublicResultsRoute
  '/api/public/signals': typeof ApiPublicSignalsRoute
  '/api/public/vip': typeof ApiPublicVipRouteWithChildren
  '/api/public/vip/set-vip': typeof ApiPublicVipSetVipRoute
  '/api/public/vip/sync': typeof ApiPublicVipSyncRoute
  '/api/public/vip/users': typeof ApiPublicVipUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/results': typeof ApiPublicResultsRoute
  '/api/public/signals': typeof ApiPublicSignalsRoute
  '/api/public/vip': typeof ApiPublicVipRouteWithChildren
  '/api/public/vip/set-vip': typeof ApiPublicVipSetVipRoute
  '/api/public/vip/sync': typeof ApiPublicVipSyncRoute
  '/api/public/vip/users': typeof ApiPublicVipUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/results': typeof ApiPublicResultsRoute
  '/api/public/signals': typeof ApiPublicSignalsRoute
  '/api/public/vip': typeof ApiPublicVipRouteWithChildren
  '/api/public/vip/set-vip': typeof ApiPublicVipSetVipRoute
  '/api/public/vip/sync': typeof ApiPublicVipSyncRoute
  '/api/public/vip/users': typeof ApiPublicVipUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/results'
    | '/api/public/signals'
    | '/api/public/vip'
    | '/api/public/vip/set-vip'
    | '/api/public/vip/sync'
    | '/api/public/vip/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/results'
    | '/api/public/signals'
    | '/api/public/vip'
    | '/api/public/vip/set-vip'
    | '/api/public/vip/sync'
    | '/api/public/vip/users'
  id:
    | '__root__'
    | '/'
    | '/api/public/results'
    | '/api/public/signals'
    | '/api/public/vip'
    | '/api/public/vip/set-vip'
    | '/api/public/vip/sync'
    | '/api/public/vip/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicResultsRoute: typeof ApiPublicResultsRoute
  ApiPublicSignalsRoute: typeof ApiPublicSignalsRoute
  ApiPublicVipRoute: typeof ApiPublicVipRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/results': {
      id: '/api/public/results'
      path: '/api/public/results'
      fullPath: '/api/public/results'
      preLoaderRoute: typeof ApiPublicResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/signals': {
      id: '/api/public/signals'
      path: '/api/public/signals'
      fullPath: '/api/public/signals'
      preLoaderRoute: typeof ApiPublicSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vip': {
      id: '/api/public/vip'
      path: '/api/public/vip'
      fullPath: '/api/public/vip'
      preLoaderRoute: typeof ApiPublicVipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vip/set-vip': {
      id: '/api/public/vip/set-vip'
      path: '/set-vip'
      fullPath: '/api/public/vip/set-vip'
      preLoaderRoute: typeof ApiPublicVipSetVipRouteImport
      parentRoute: typeof ApiPublicVipRoute
    }
    '/api/public/vip/sync': {
      id: '/api/public/vip/sync'
      path: '/sync'
      fullPath: '/api/public/vip/sync'
      preLoaderRoute: typeof ApiPublicVipSyncRouteImport
      parentRoute: typeof ApiPublicVipRoute
    }
    '/api/public/vip/users': {
      id: '/api/public/vip/users'
      path: '/users'
      fullPath: '/api/public/vip/users'
      preLoaderRoute: typeof ApiPublicVipUsersRouteImport
      parentRoute: typeof ApiPublicVipRoute
    }
  }
}

interface ApiPublicVipRouteChildren {
  ApiPublicVipSetVipRoute: typeof ApiPublicVipSetVipRoute
  ApiPublicVipSyncRoute: typeof ApiPublicVipSyncRoute
  ApiPublicVipUsersRoute: typeof ApiPublicVipUsersRoute
}

const ApiPublicVipRouteChildren: ApiPublicVipRouteChildren = {
  ApiPublicVipSetVipRoute: ApiPublicVipSetVipRoute,
  ApiPublicVipSyncRoute: ApiPublicVipSyncRoute,
  ApiPublicVipUsersRoute: ApiPublicVipUsersRoute,
}

const ApiPublicVipRouteWithChildren = ApiPublicVipRoute._addFileChildren(
  ApiPublicVipRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicResultsRoute: ApiPublicResultsRoute,
  ApiPublicSignalsRoute: ApiPublicSignalsRoute,
  ApiPublicVipRoute: ApiPublicVipRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
